### ISSUE TITLE
注意：：框架的 grad_fn.xxx  不一样触发的BUG

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/OneFlow-Pruning#6]
##  grad_fn_name 
> 问题来源: https://github.com/Oneflow-Inc/OneFlow-Pruning/issues/5#issuecomment-1503512583

| 框架|**grad_fn_name**  | 
|---|---|
|PyTorch| CatBackward0|
| OneFlow | concat_backward|

运行下面 demo.py 代码可以打印的 grad_fn_name 为 “**CatBackward0**”

_**demo.py**_  
```python

1. import  torch
2. 
3. # create two tensors
4. x1 = torch.randn(2, 3, requires_grad=True)  # create a random tensor with shape (2, 3) and requires gradient
5. x2 = torch.randn(2, 4, requires_grad=True)  # create a random tensor with shape (2, 4) and requires gradient
6. 
7. # concatenate the tensors along the second dimension
8. cat = torch.cat([x1, x2], dim=1)  # concatenate the two tensors along the second dimension
9. 
10. # get the name of the function that created the tensor
11. grad_fn_name = cat.grad_fn.name()  # get the name of the function that created the tensor
12. 
13. # print the name of the function
14. print(grad_fn_name)  # print the name of the function that created the tensor

```

将第一行 `import torch`  改为 `import oneflow as torch` 后再次运行 第 14打印结果 为 “**concat_backward**” 。

## grad_fn.next_functions
 |框架| grad_fn.next_functions|
| ---|---|
| PyTorch|((<AccumulateGrad object at 0x7ffa1c13bdf0>, 0), (<AccumulateGrad object at 0x7ffa1c13bd30>, 0))  |
|OneFlow|[<accumulate_grad at 0x562275241900>, <accumulate_grad at 0x562275208500>] |

运行下面 demo.py 代码可以打印的 grad_fn.next_functions 结果： 
 “**_((<AccumulateGrad object at 0x7ffa1c13bdf0>, 0), (<AccumulateGrad object at 0x7ffa1c13bd30>, 0))_**”

**_demo.py_**
```python3
1. import  torch
2. 
3. # create two tensors
4. x1 = torch.randn(2, 3, requires_grad=True)  # create a random tensor with shape (2, 3) and requires gradient
5. x2 = torch.randn(2, 4, requires_grad=True)  # create a random tensor with shape (2, 4) and requires gradient
6. 
7. # concatenate the tensors along the second dimension
8. cat = torch.cat([x1, x2], dim=1)  # concatenate the two tensors along the second dimension
9. 
10. # get the next functions in the computation graph of cat
11. next_functions = cat.grad_fn.next_functions
12. print(next_functions)
```
将第一行 `import torch`  改为 `import oneflow as torch` 后再次运行 第 12 行打印结果: **_[<accumulate_grad at 0x562275241900>, <accumulate_grad at 0x562275208500>]_** 

## 导致的代码兼容性问题

VainF/Torch-Pruning 中 写死的 "catbackward" in grad_fn.name().lower(): 代码 并不适合 oneflow框架( **concat_backward**) ,从而触发 分组失败，从而导致剪枝失败等一系列问题。
https://github.com/VainF/Torch-Pruning/blob/69902e8d0b66db6342a2f53c99d2ff1bc5764d11/torch_pruning/dependency.py#L694
  ```
              elif "catbackward" in grad_fn.name().lower():
                    module = ops._ConcatOp()
                elif "split" in grad_fn.name().lower():
                    module = ops._SplitOp()
                elif "view" in grad_fn.name().lower() or 'reshape' in grad_fn.name().lower():
                    module = ops._ReshapeOp()
                else:
                    # treate other ops as element-wise ones, like Add, Sub, Div, Mul.
                    module = ops._ElementWiseOp(grad_fn.name())
                gradfn2module[grad_fn] = module
```

注意： 同样的写死的 **_and "accumulategrad" in f[0].name().lower()_** 代码 并不兼容 oneflow框架
https://github.com/Oneflow-Inc/OneFlow-Pruning/blob/813d86981fcd3d66ba0842c4c2bd569cd5e83a42/torch_pruning/dependency.py#L701-L705

## 注意事项
注意其他算子应该也可能存在同样问题。
## 解决方案 
直接修改，，，或者。。。。。。

**Comment by BBuf** [comment]
这个问题是因为我们的autograd engine在添加node的时候是在autograd的interperter那里直接添加的expr.op_type_name 作为反向节点name，但是我们的op_type_name和pytorch有一些区别。还有就是后缀又一点区别，PyTorch是大写的并且没有加下划线，其实也简单我稍后提个pr修改

**Comment by ccssu** [comment]
## **“OperatorName + Backward + index"**

**PyTorch中 反向节点name 命名规则为 “OperatorName + Backward + index“** 

Pytorch框架在derivatives.yaml中定义算子求导。
https://github.com/pytorch/pytorch/blob/ccc9a3d726b1f249daffa442460b70fb50a0ee2e/tools/autograd/derivatives.yaml#L204
![image](https://user-images.githubusercontent.com/109639975/231638419-991a2253-a50c-4695-a447-91eb7d766e10.png)



PyTorch会自动帮我们生成一个AddBackward0的类。这个类我们应该都很熟悉，当我们使用autograd的时候，Tensor里的grad_fn就是这样的类名，其命名规则就是 “OperatorName + Backward + index” , 体现在 下面  第 10 行 `std::string name() const override { return "AbsBackward0"; }`

```c++
1. // File: torch/csrc/autograd/generated/Functions.h
2. 
3. #pragma once
4. 
5. // @generated from ../tools/autograd/templates/Functions.h
6. 。。。
7. struct TORCH_API AbsBackward0 : public TraceableFunction {
8.   using TraceableFunction::TraceableFunction;
9.   variable_list apply(variable_list&& grads) override;
10.   std::string name() const override { return "AbsBackward0"; }
11.   void release_variables() override {
12.     std::lock_guard<std::mutex> lock(mutex_);
13.     self_.reset_data();
14.   }
15. 
16.   SavedVariable self_;
17. 
18. };
19. 
```


## 可能令人困惑的命名 AddBackward_**0**_ 其中 的 **_0_** 
> pytorch官方给的介绍
https://github.com/pytorch/pytorch/blob/51ff9ce9974b32ba77dd00241a3dc6357f76ba82/tools/autograd/derivatives.yaml#L3 

```yaml
# Defines derivative formulas and Python signatures of methods on Variable
#
# Note about possibly confusing nomenclature: An 'output gradient' is the
# gradient of an output of a forward function. Output gradients are used as
# the inputs to backward functions. `grads` is a vector of output gradients,
# and `grad == grads[0]`, in all the derivative formulas in this file.
# An 'input gradient' is the gradient of an input to a forward function.
# Input gradients are the outputs of backward functions, corresponding to the
# input names included in the derivative formulas defined in this file.
# Also, every time we talk computing "gradient" we actually mean computing
# the vector jacobian product using the given 'output gradient' as the vector.
```
